# Generated by Django 4.0.1 on 2022-01-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.Category'),
        ),
    ]
