# Generated by Django 4.0.1 on 2022-01-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact_feedback_voting_delete_gamenight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
