# Generated by Django 4.0.1 on 2022-01-19 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_voting_contact_delete_feedback_delete_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('location', models.CharField(max_length=300)),
                ('attendees', models.ManyToManyField(related_name='attended', to='api.Contact')),
                ('games', models.ManyToManyField(related_name='gamenights', to='api.Game')),
                ('invitees', models.ManyToManyField(related_name='invited', to='api.Contact')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option1', to='api.game')),
                ('option10', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option10', to='api.game')),
                ('option2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option2', to='api.game')),
                ('option3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option3', to='api.game')),
                ('option4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option4', to='api.game')),
                ('option5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option5', to='api.game')),
                ('option6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option6', to='api.game')),
                ('option7', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option7', to='api.game')),
                ('option8', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option8', to='api.game')),
                ('option9', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='option9', to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamenights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option2', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option3', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option4', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option5', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option6', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option7', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option8', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option9', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('option10', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='api.contact')),
                ('gamenight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='api.gamenight')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('people_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game1_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game2_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game3_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game4_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('game5_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.contact')),
                ('gamenight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.gamenight')),
            ],
        ),
    ]
