# Generated by Django 4.0.1 on 2022-01-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_contact_voting_invitee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'first_name', 'last_name', 'email'), name='unique-contact'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('gamenight', 'attendee'), name='unique-feedback'),
        ),
        migrations.AddConstraint(
            model_name='gamenight',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique-gamenight'),
        ),
        migrations.AddConstraint(
            model_name='voting',
            constraint=models.UniqueConstraint(fields=('gamenight', 'invitee'), name='unique-vote'),
        ),
    ]
