# Generated by Django 4.0.1 on 2022-01-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_gamenight_option1_alter_gamenight_option10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenight',
            name='player_num',
        ),
    ]
