# Generated by Django 4.0.1 on 2022-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_gamenight_player_num'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamenight',
            name='unique-gamenight',
        ),
        migrations.AddField(
            model_name='gamenight',
            name='rid',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='gamenight',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'rid'), name='unique-gamenight'),
        ),
    ]
