# Generated by Django 4.0.1 on 2022-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_gamenight_unique-gamenight_gamenight_rid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenight',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='gamenights', to='api.Game'),
        ),
    ]
