# Generated by Django 4.0.1 on 2022-01-20 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_feedback_game1_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenight',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option10',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='gamenight',
            name='option9',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option10',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option9',
        ),
        migrations.AddField(
            model_name='gamenight',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='options', to='api.Game'),
        ),
        migrations.AddField(
            model_name='voting',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='api.game'),
        ),
        migrations.AddField(
            model_name='voting',
            name='vote',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
