# Generated by Django 4.0.1 on 2022-01-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_gamenight_option1_remove_gamenight_option10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='api.game'),
        ),
    ]
