# Generated by Django 4.0.1 on 2022-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_voting_unique-vote_voting_unique-vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenight',
            name='status',
            field=models.CharField(choices=[('Voting', 'Voting'), ('Finalized', 'Finalized'), ('Cancelled', 'Cancelled')], default='Voting', max_length=9),
        ),
    ]
