# Generated by Django 4.0.1 on 2022-01-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_voting_unique-vote_voting_unique-vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefeedback',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.feedback'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.game'),
        ),
    ]
