# Generated by Django 4.0.1 on 2022-01-21 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_gamefeedback_feedback_alter_gamefeedback_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('people_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='gamenight',
        ),
        migrations.RemoveConstraint(
            model_name='gamefeedback',
            name='unique-game-feedback',
        ),
        migrations.RemoveField(
            model_name='gamefeedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.contact'),
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='gamenight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.gamenight'),
        ),
        migrations.AddConstraint(
            model_name='gamefeedback',
            constraint=models.UniqueConstraint(fields=('gamenight', 'attendee', 'game'), name='unique-game-feedback'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalfeedback', to='api.contact'),
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='gamenight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalfeedback', to='api.gamenight'),
        ),
        migrations.AddConstraint(
            model_name='generalfeedback',
            constraint=models.UniqueConstraint(fields=('gamenight', 'attendee'), name='unique-feedback'),
        ),
    ]
