# Generated by Django 4.0.1 on 2022-01-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_gamenight_status'),
        ('api', '0021_generalfeedback_remove_feedback_attendee_and_more'),
    ]

    operations = [
    ]
