# Generated by Django 4.0.1 on 2022-01-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20220123_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField()),
                ('gamenight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='api.gamenight')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='api.contact')),
            ],
        ),
    ]
