# Generated by Django 4.0.1 on 2022-01-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rsvp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamefeedback',
            name='unique-game-feedback',
        ),
        migrations.RemoveField(
            model_name='gamefeedback',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='gamefeedback',
            name='gamenight',
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='generalfeedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.generalfeedback'),
        ),
        migrations.AddConstraint(
            model_name='gamefeedback',
            constraint=models.UniqueConstraint(fields=('generalfeedback', 'game'), name='unique-game-feedback'),
        ),
    ]
