# Generated by Django 4.0.1 on 2022-01-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_gamefeedback_unique-game-feedback_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamefeedback',
            name='unique-game-feedback',
        ),
        migrations.RemoveField(
            model_name='gamefeedback',
            name='generalfeedback',
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.contact'),
        ),
        migrations.AddField(
            model_name='gamefeedback',
            name='gamenight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.gamenight'),
        ),
        migrations.AddConstraint(
            model_name='gamefeedback',
            constraint=models.UniqueConstraint(fields=('gamenight', 'attendee', 'game'), name='unique-game-feedback'),
        ),
    ]
