# Generated by Django 4.0.1 on 2022-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_gamefeedback_unique-game-feedback_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(fields=('gamenight', 'invitee'), name='unique-rsvp'),
        ),
    ]
