# Generated by Django 4.0.1 on 2022-01-25 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rsvp_unique-rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalfeedback',
            name='location_rating',
        ),
        migrations.AddField(
            model_name='generalfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.contact'),
        ),
        migrations.AlterField(
            model_name='gamefeedback',
            name='gamenight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.gamenight'),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='people_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
