# Generated by Django 4.0.1 on 2022-01-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_generalfeedback_gamenight'),
        ('api', '0027_remove_generalfeedback_location_rating_and_more'),
    ]

    operations = [
    ]
