# Generated by Django 4.0.1 on 2022-01-25 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20220125_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfeedback',
            name='location_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
