# Generated by Django 4.0.1 on 2022-01-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_generalfeedback_location_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefeedback',
            name='gamenight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefeedback', to='api.gamenight'),
        ),
    ]
