# Generated by Django 4.0.1 on 2022-01-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_gamefeedback_gamenight'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenight',
            name='feedback_task',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
